#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 获取当前的分支
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

# 禁止直接在主分支上修改代码
if [ "$current_branch" = "main" ] || [ "$current_branch" = "master" ] ; then
    echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    echo ""
    echo "禁止直接在主分支上修改代码！"
    echo ""
    echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    exit 1
fi

# 提交代码之前，检测是否符合代码规范
yarn lint
